version: "3.9"

services:
  web:
    build: .
    command:  >
      sh -c "python manage.py migrate --settings=ChickoMenu.settings.development &&
             python manage.py runserver 0.0.0.0:8000 --settings=ChickoMenu.settings.development"
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - "./.env.db"
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db

  redis:
    image: redis:alpine
    container_name: redis

  celery:
    build: ./
    command: celery -A ChickoMenu worker -l info 
    volumes:
      - ./:/usr/src/app/
    depends_on:
      - redis

  app:
    build: ./
    command: celery -A ChickoMenu beat -l info
    volumes:
      - ./:/usr/src/app/
    depends_on:
      - redis
  dashboard:
      build: ./
      command: celery -A ChickoMenu --broker=redis://redis:6379 flower 
      ports:
        - 5555:5555
      depends_on:
        - web
        - redis
        - celery
volumes:
  postgres_data: